# -*- coding: utf-8 -*-
"""ASSIGNMENT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNqwHIlxwtbFa625NojkrUB41LYC5Anv
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import linprog

# =====================================================
# PROBLEM DEFINITION
# =====================================================

print("="*50)
print("AI INTERNSHIP RECRUITMENT OPTIMIZATION")
print("="*50)

# Objective Function
# Max Z = 8x1 + 5x2

c = [-8, -5]

# Constraints

A = [
    [2, 1],
    [3, 2]
]

b = [
    20,
    30
]

# =====================================================
# SIMPLEX SOLVER
# =====================================================

result = linprog(
    c,
    A_ub=A,
    b_ub=b,
    method='highs'
)

# =====================================================
# RESULTS
# =====================================================

x1 = result.x[0]
x2 = result.x[1]

max_contribution = -result.fun

print("\nOPTIMAL SOLUTION")

print(f"AI Interns   (x1) = {x1:.2f}")

print(f"Data Interns (x2) = {x2:.2f}")

print(
    f"\nMaximum Contribution = {max_contribution:.2f}"
)

# =====================================================
# RESOURCE USAGE
# =====================================================

mentor_used = 2*x1 + x2

budget_used = 3*x1 + 2*x2

print("\nRESOURCE USAGE")

print(
    f"Mentor Hours Used = {mentor_used:.2f}/20"
)

print(
    f"Budget Used = {budget_used:.2f}/30"
)

# =====================================================
# FEASIBLE REGION
# =====================================================

x = np.linspace(0,15,400)

mentor_line = 20 - 2*x

budget_line = (30 - 3*x)/2

plt.figure(figsize=(8,6))

plt.plot(
    x,
    mentor_line,
    label="2x1 + x2 = 20"
)

plt.plot(
    x,
    budget_line,
    label="3x1 + 2x2 = 30"
)

plt.xlim(0,15)

plt.ylim(0,25)

plt.xlabel("AI Interns (x1)")

plt.ylabel("Data Interns (x2)")

plt.title(
    "Feasible Region"
)

plt.legend()

plt.grid()

plt.show()

# =====================================================
# OPTIMAL POINT VISUALIZATION
# =====================================================

plt.figure(figsize=(8,6))

plt.plot(
    x,
    mentor_line,
    label="Mentor Hours Constraint"
)

plt.plot(
    x,
    budget_line,
    label="Budget Constraint"
)

plt.scatter(
    x1,
    x2,
    s=250,
    marker='*',
    label='Optimal Solution'
)

plt.annotate(
    f"({x1:.1f},{x2:.1f})",
    (x1,x2)
)

plt.xlim(0,15)

plt.ylim(0,25)

plt.xlabel(
    "AI Interns (x1)"
)

plt.ylabel(
    "Data Interns (x2)"
)

plt.title(
    "Optimal Hiring Strategy"
)

plt.legend()

plt.grid()

plt.show()

# =====================================================
# BAR CHART
# =====================================================

labels = [
    "AI Interns",
    "Data Interns"
]

values = [
    x1,
    x2
]

plt.figure(figsize=(6,4))

plt.bar(
    labels,
    values
)

plt.title(
    "Optimal Number of Interns"
)

plt.ylabel(
    "Quantity"
)

plt.show()